# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'otpless_ios_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for otpless_ios_demo
      pod 'OtplessSDK', '2.0.0'

  target 'otpless_ios_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'otpless_ios_demoUITests' do
    # Pods for testing
  end

end
